url: https://stockholm.ai

collections:
  people:
    output: true
    permalink: /:collection/:title
  meetups:
    output: true
    permalink: /:collection/:title
  study-groups:
    output: true
    permalink: /:collection/:title
  distilling-ais:
    output: true
    permalink: /:collection/:title
  blogs:
    output: true
    permalink: /:collection/:title
  posts:
    output: true
    permalink: /:collection/:title
  companies:
    output: true
    permalink: /:collection/:title

# collections_dir: collections

defaults:
  - scope:
      path: ""
      type: people
    values:
      layout: people
  - scope:
      path: ""
      type: meetups
    values:
      layout: meetup
  - scope:
      path: ""
      type: study-groups
    values:
      layout: study-group
  - scope:
      path: ""
      type: distilling-ais
    values:
      layout: distilling-ai
  - scope:
      path: ""
      type: blogs
    values:
      layout: blog
  - scope:
      path: ""
      type: companies
    values:
      layout: company

exclude:
  - CODEOWNERS
  - Dockerfile
  - LICENSE
  - README.md
  - TODO.md
  - convert_to_favicon.sh
  - local_start.sh
  - local_syncer.sh
  - server/
  - start.sh
  - supervisord.conf
  - syncer.sh

# Build settings
markdown: kramdown
permalink: /:categories/:title
